### ISSUE TITLE
Renaming chapters

### ISSUE THREAD

**Issue by keikoro** [DjangoGirls/translation-guide#2]
Heya,

I'd suggest renaming the file `when_its_ready.md` to either `publishing.md` or `publishing_translations.md` to be more consistent with the chapter's (slightly corrected) headline/content.

**Comment by olasitarska** [comment]
Hi Kerstin,

Thanks for the suggestion, however, we decide not to change the name of the chapters in any gitbook book, as it destroys the URLs.

Thanks!
Ola
